### ISSUE TITLE
Open Babel problem during installation 

### ISSUE THREAD

**Issue by mohamedmarzouk2020** [pharmai/plip#102]
I am trying to install plip by pip and Canda-froge, but the same error of Open Babel edition. 

the error message
**_Error: SWIG failed. Is Open Babel installed?
    You may need to manually specify the location of Open Babel include and library directories. For example:
      python setup.py build_ext -I/usr/local/include/openbabel3 -L/usr/local/lib
      python setup.py install

ERROR: Command errored out with exit status 1: /misc/home/marzouk/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-g4qywcf7/openbabel/setup.py'"'"'; __file__='"'"'/tmp/pip-install-g4qywcf7/openbabel/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-nlvz99gs/install-record.txt --single-version-externally-managed --compile Check the logs for full command output._**
I installed open babel by conda but 2.4.1, but the plip needs 3.1.1 which cannot be downloaded by pip or conda

**Comment by fkaiserbio** [comment]
Please consider to use the Docker images if you run into troubles installing PLIP as described here:

https://github.com/pharmai/plip#quickstart

We cannot provide support for the installation of OpenBabel. This is distribution dependent and up to the user. You might have a look to the Docker build instructions on how to install and link the required OpenBabel version 3:

- Ubuntu 18.04: https://github.com/pharmai/plip/blob/master/Dockerfile
- Ubuntu 20.04: https://github.com/pharmai/plip/blob/master/Dockerfile.20.04

**Comment by jamesmkrieger** [comment]
but, shouldn't we be able to use our own installation of openbabel with these options? I have installed openbabel 2.4.0 from source-force and want to install plip 1.3.3 from githhub using tags and I give these options and it still says it can't find it.
