### ISSUE TITLE
OSX fails with  resource.getrlimit (supplemental.py)

### ISSUE THREAD

**Issue by reskyner** [pharmai/plip#46]
```
if os.name != 'nt':  # Resource module not available for Windows
        maxsize = resource.getrlimit(resource.RLIMIT_STACK)[-1]
        resource.setrlimit(resource.RLIMIT_STACK, (min(2 ** 28, maxsize), maxsize))
```

Causes the following error on OSX with python 3.6:

`ValueError: current limit exceeds maximum limit`

This has been encountered in a few other places, e.g.:
https://github.com/cea-hpc/clustershell/issues/285

Easily fixed by ignoring for mac, like windows. 

```
if os.name != 'nt' and platform.system() != 'Darwin':  
        maxsize = resource.getrlimit(resource.RLIMIT_STACK)[-1]
        resource.setrlimit(resource.RLIMIT_STACK, (min(2 ** 28, maxsize), maxsize))
```

**Comment by mestia** [comment]
>Causes the following error on OSX with python 3.6:

Isn't plip python2 only?

**Comment by reskyner** [comment]
Good point...

**Comment by mestia** [comment]
Actually I am wrong, just learned that plip is python3 compatible since [v1.4.0.b](https://github.com/ssalentin/plip/releases/tag/v1.4.0b)

**Comment by tonyyzy** [comment]
@reskyner @mestia 
Hey, I looked into this error, it seems to be a python bug with MacOS which was fixed not long ago. https://bugs.python.org/issue34602
If you use python3.7.4 then this issue shouldn't appear. (I tested with the 3.7.4 docker)

Alternatively, if you cloned the git repo as 'installation' method, you can comment out these three lines. As long as you are not doing something crazy, it should be safe.
https://github.com/ssalentin/plip/blob/8c36e35fb7f44992a14db4f3626316892a77e81f/plip/modules/supplemental.py#L392-L394

**Comment by fkaiserbio** [comment]
fixed in https://github.com/pharmai/plip/commit/9ae38d3445f24624b2e464725d5e799e3edc5391
