### ISSUE TITLE
Glutamic acid as hydrogen bond donor

### ISSUE THREAD

**Issue by tonyyzy** [pharmai/plip#47]
Hi!

As shown below, a hydrogen bond is predicted between glutamic acid's side-chain with an oxygen. Under physiological pH, the side-chain should be deprotonated hence shouldn't act as a hydrogen bond donor?

<img width="255" alt="Screenshot 2019-08-08 at 13 44 26" src="https://user-images.githubusercontent.com/38984697/62704442-4fdb5600-b9e3-11e9-91bd-8bfe39418f19.png">

**Comment by fkaiserbio** [comment]
- related to #50 and will be fixed in future release
