### ISSUE TITLE
Please port to Python3

### ISSUE THREAD

**Issue by tillea** [pharmai/plip#48]
Hello,
the Debian Med team is maintaining PLIP for official Debian. The recently released Debian 10 was the last Debian release featuring Python2 since this programming language is EOL. If you are interested that we continue to maintain PLIP in official Debian (and that users of other modern distributions will have no problems to install PLIP on their systems) I'd recommend you port your code to Python3. The 2to3 tool might be of great help here.
Kind regards, Andreas.

**Comment by mestia** [comment]
Hi Andreas,
plip is actually python3 compatible, however it depends on python3-openbabel which is not yet in the archive, but some work is already done on the salsa repository. Once python3-openbabel is accepted into unstable I'll update plip packaging.
Best, Alex

**Comment by tillea** [comment]
On Tue, Sep 17, 2019 at 02:29:45PM +0000, Alex Mestiashvili wrote:
> plip is actually python3 compatible, however it depends on
> python3-openbabel which is not yet in the archive, but some work is
> already done on the salsa repository. Once python3-openbabel is
> accepted into unstable I'll update plip packaging.

python3-openbabel is now in unstable:

$ rmadison python3-openbabel
python3-openbabel | 2.4.1+dfsg-4  | buildd-unstable | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x
python3-openbabel | 2.4.1+dfsg-4  | unstable        | amd64, arm64, armel, armhf, i386, mips64el, mipsel, ppc64el, s390x

Cheers,
    Olly

**Comment by xrobin** [comment]
At this point I would not consider PLIP compatible with python 3. See issues #49 #50 and #53.

**Comment by tillea** [comment]
I'd be super happy if you would ping this issue once the other issues might have been solved.

**Comment by vjhaupt** [comment]
We are having a look into this and will start solving the Python 3 issues in the next days.

**Comment by fkaiserbio** [comment]
FYI: We have started the migration to Python 3 that will solve lots of issues and offers Docker support. Please be patient, we are working hard to bring you a new PLIP experience soon.

**Comment by koyurion** [comment]
Hi, I wanna to seek help.  How should I install PLIP in python3? As python2 is not supported in 2020...

**Comment by vjhaupt** [comment]
We will release PLIP 2 very soon. This will come with full Python 3 and OpenBabel 3 support and will be also shipped as Docker image.

**Comment by fkaiserbio** [comment]
I have released PLIP v2.1.0-beta. It should hopefully solve all Python 3 issues. You can find it under [Releases](https://github.com/pharmai/plip/releases). I would appreciate any feedback to turn it into a stable release soon.

With the awesomeness of the new [Singularity Image](https://github.com/pharmai/plip/releases/download/v2.1.0-beta/pharmai-plip-v2.1.0-beta.simg), you can run the PLIP with a single command on any recent Linux machine:

`./pharmai-plip-v2.1.0-beta.simg -i 1vsn -y`
