### ISSUE TITLE
Unstable results and large angle differences with Python 3.6

### ISSUE THREAD

**Issue by xrobin** [pharmai/plip#49]
We are porting SWISS-MODEL to Python 3 (3.6.6 compiled with GCCcore-7.3.0). I am having trouble with the tests related to PLIP. It seems that the ordering of residues in the XML output (bs_residue) is arbitrary, and changes from run to run. This also results in slightly different numerical results from run to run. This would be fine, but some changes are surprisingly large.

To demonstrate the problem, I ran the following command on [4DST](https://www.rcsb.org/structure/4DST):

    wget https://files.rcsb.org/download/4DST.pdb
    plipcmd.py -f 4DST.pdb --name 4DST_report -o . -x

with PLIP 1.4.5 (from the `stable` branch), installed with `pip install .` under different conditions. I am attaching the XML outputs below (gzipped because GitHub doesn't accept XML directly).

- First with Python 2.7.11: [4DST_report_2.7.xml.gz](https://github.com/ssalentin/plip/files/4058182/4DST_report_2.7.xml.gz)
- Then with Python 3.6.6 (run 1): [4DST_report_3.6_1.xml.gz](https://github.com/ssalentin/plip/files/4058187/4DST_report_3.6_1.xml.gz)
- Then again with Python 3.6.6 (run 2)" [4DST_report_3.6_2.xml.gz](https://github.com/ssalentin/plip/files/4058188/4DST_report_3.6_2.xml.gz)

Running `diff -u 4DST_report_3.6_1.xml 4DST_report_3.6_2.xml` higlights changes in ordering and rounding, which are fairly minor. But some changes are uncomfortably large. For instance if you compare the angles of the Pi stack between GCP:202 and PHE:28, the first decimal is off:

```
-          <angle>80.14</angle>
-          <offset>1.24</offset>
+          <angle>80.62</angle>
+          <offset>1.28</offset>
```

Is this expected?

Note that with Python 2.7, I was getting 80.21 reliably as an angle, and that this is what I get with the web version of PLIP.

**Comment by vjhaupt** [comment]
We will have a look into that. Just give me some days...

**Comment by fkaiserbio** [comment]
Hi @xrobin 
Could you please check with latest version from `feature/docker` branch on Python 3 and OpenBabel 3?
It seems that the slight differences in the angle might be related to #55.
Thank you!

**Comment by xrobin** [comment]
I asked our sysadmins to install OpenBabel 3 on our system and will keep you posted with the results.

**Comment by fkaiserbio** [comment]
Fantastic, thank you! There will be a major PLIP release soon. We are making steady progress :+1:

**Comment by fkaiserbio** [comment]
Fixed in https://github.com/pharmai/plip/commit/49b0f8ef0ecbbeadf5f15a41023671f01425d50d. It turned out that ring detection in OpenBabel is non-deterministic due to the fact that ligand atoms are renumbered arbitrarily upon parsing. This resulted in minor differences in angles and distances for Pi-Stacking interactions. It is now ensured that PLIP always uses the same atom order as defined in the input PDB and hence, Pi-Stacking is now always detected identical.

**Comment by xrobin** [comment]
I can confirm that I am now always getting the same angle. Thanks!
