### ISSUE TITLE
python modules PLIP is unable to import pybel & openbabel with OB 3.x

### ISSUE THREAD

**Issue by CharlesHahn** [pharmai/plip#52]
i think this should be a little bug.
In the "supplemental.py" and "detection.py" scripts, the way to import pybel & openbabel is wrong. 
see https://open-babel.readthedocs.io/en/latest/UseTheLibrary/migration.html#python-module
It should be like:

    # External libraries
    # import pybel
    from openbabel import pybel
    # from pybel import *
    from openbabel.pybel import *
    # from openbabel import *
    from openbabel.openbabel import *

good wish!

**Comment by nys08** [comment]
We are also facing similar issues, could you please specify the version you are using for : 
- plip
- pybel
- open babel
- python

Thanks :)

**Comment by CharlesHahn** [comment]
@nys08 sorry to answer so late.
version:
open babel 3.0.0
plip              1.4.2
python         3.7.0

plip is installed by **pip** which seems unable to add plip into environment. So i also downloaded the **plip-stable** from https://plip.biotec.tu-dresden.de/plip-web/plip/index, and ran plipcmd.py like "python plipcmd.py " . Then , after modified the supplemental.py in site-pakages of python and plip files of plip-stable, plip is still unable to pass all unittests, but it seems to work fine with "plip -i 1vsn -yv". I have not fully test it。

And pybel, there are two "pybel", one is pybel in openbabel, the other is **PyBEL** which is different from the pybel in openbabel. i didn't install PyBEL. In fact, after "pip install openbabel", i could import pybel from openbabel.openbabel already.

good wish!

**Comment by nys08** [comment]
Thanks a lot for your answer. I will try your way. 
All the best.

**Comment by o7o** [comment]
I can not install plip when I used Windows 10, openbabel-3.0.0, pymol 2.3.0 from Christoph Gohlke and plip 1.4.5. I have tried on python 3.6; 3.7; or 3.8. It's different, when I used openbabel-2.4.1.

I am waiting the solution, too. Hope the best.

**Comment by fkaiserbio** [comment]
- fixed in `feature/docker` and with b889e09b5f7aeefee786f41f93d02529871087c4 in `stable`
