### ISSUE TITLE
ValueError: inchikey is not a recognised Open Babel format

### ISSUE THREAD

**Issue by koyurion** [pharmai/plip#59]
Hi, when I run the test_literature_validated.py, it has some errors asbelow:
```
Error
Traceback (most recent call last):
  File "D:\anaconda\envs\my-python2.7\lib\unittest\case.py", line 329, in run
    testMethod()
  File "E:\plip-stable\plip\test\test_literature_validated.py", line 469, in test_1aku
    tmpmol.characterize_complex(ligand)
  File "E:\plip-stable\plip\modules\preparation.py", line 1409, in characterize_complex
    lig_obj = Ligand(self, ligand)
  File "E:\plip-stable\plip\modules\preparation.py", line 1003, in __init__
    self.inchikey = self.molecule.write(format='inchikey')
  File "D:\anaconda\envs\my-python2.7\lib\site-packages\pybel.py", line 527, in write
    format)
ValueError: inchikey is not a recognised Open Babel format
```

my environment info:
![image](https://user-images.githubusercontent.com/32454333/81146042-1e131200-8faa-11ea-9756-a89460f1b939.png)

**Comment by vjhaupt** [comment]
How exactly did you install PLIP? There is no version 1.4.5

**Comment by koyurion** [comment]
I install plip by  "python setup_conda.py install"

**Comment by koyurion** [comment]
![image](https://user-images.githubusercontent.com/32454333/81148206-6df3d800-8fae-11ea-81c0-048923261f6a.png)

**Comment by vjhaupt** [comment]
I see. Seems to be an issue in OpenBabel. Could you check whether your OpenBabel installation is okay by following some of the examples in https://openbabel.org/docs/current/UseTheLibrary/PythonDoc.html

Try to write an InChiKey from a molecule. If this fails, you have to fix your openbabel installation.

**Comment by vjhaupt** [comment]
Looks like an upstream issue in OpenBabel: see openbabel/openbabel#1898 and openbabel/openbabel#2194

**Comment by vjhaupt** [comment]
related to upstream issue
