### ISSUE TITLE
conda forge package

### ISSUE THREAD

**Issue by hadim** [pharmai/plip#62]
I have created a conda forge package for plip here: https://github.com/conda-forge/staged-recipes/pull/11680

I can add you as a maintainer if you want, just leave a comment on the PR.

**Comment by hadim** [comment]
Also for the `plip` command, I would suggest you use the following: https://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

Instead of using `alias plip='python ~/pliptool/plip/plipcmd.py'`

**Comment by fkaiserbio** [comment]
Thanks for your effort! I've updated to the use of an appropriate entry point in 91207bb832a73722aa0dcfb3080197e73616418c
