### ISSUE TITLE
Create ARM compatible docker images

### ISSUE THREAD

**Issue by navanchauhan** [pharmai/plip#65]
The current images aren't ARM compatible and give exec error when you try to execute them

**Comment by fkaiserbio** [comment]
Hi @navanchauhan!

This is an interesting feature request. I've devised an experimental multi-architecture build using Docker's `buildx` feature, which is available in >19.03. However, this feature is still considered experimental according to the [docs](https://docs.docker.com/buildx/working-with-buildx/). Please test the image of the new beta release `v2.1.3-beta`:

`docker pull pharmai/plip:2.1.3-beta-multi`

If you have positive feedback, we might integrate multi-architecture builds in our deployment pipeline.

**Comment by navanchauhan** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/29234112/86354641-06dd6180-bc87-11ea-81f6-22ec880dd28a.png">

It is only generating a core file (which I think is the Docker Core Dump File). I was testing on a Pi Zero ( armv6l ), I'll revert back once my Pi 4 comes

**Comment by fkaiserbio** [comment]
Unfortunately, we cannot offer support `linux/arm/v6`, because the Ubuntu 18.04 base image does not exist for this architecture (see [here](https://hub.docker.com/layers/ubuntu/library/ubuntu/18.04/images/sha256-c32bd2e76e7688eeb1bb39754fff7cdfc571626fc1abfded4f82a90de79f8d10?context=explore)). Please use `linux/arm/v7` or `linux/arm64/v8` compatible hardware instead.

**Comment by navanchauhan** [comment]
Understood, it would be a headache managing all of this. Even Debian's testing version bullseye does not have openbabel3 package available right now, so making a Debian based image will also not work. I'll ping back on this issue once I get some alternative ARM hardware

**Comment by mestia** [comment]
Debian testing is shipping openbabel 3.1.1, see https://packages.debian.org/bullseye/openbabel
I didn't look if other deps are available form ARM, but the dockerfile can be as easy as `apt-get install plip` from Debian testing or unstable.

**Comment by navanchauhan** [comment]
The only package which is not available is libopenbabel6 ( although libopenbabel5 and libopenbabel7 are available)

**Comment by navanchauhan** [comment]
Runs flawlessly, tested on `Ubuntu-20.04 Server Image for ARM+Raspi` 👍

**Comment by fkaiserbio** [comment]
Fantastic thanks for you feedback! We integrate ARM builds into our pipeline from now on.
