### ISSUE TITLE
How does PLIP handle multiple models in a PDB structure?

### ISSUE THREAD

**Issue by koyurion** [pharmai/plip#69]
Hi, I am sorry to bother you. I have some confusions about how does PLIP handle multiple models in a PDB structure.

> just take 1lxf.pdb(downloaded in RCSB by [https://files.rcsb.org/download/1lxf.pdb])，it has 30 MODELs.

![image](https://user-images.githubusercontent.com/32454333/88461855-ea28f800-ced9-11ea-9195-076162dbef7c.png)

> So I am confused. Which  MODEL would be used in PLIP? Is the first one? Or choose one according to some rules?

> Thanks for your time to read this message! Looking forward to you

**Comment by fkaiserbio** [comment]
Dear koyurion,

currently PLIP handles only the first model it sees in a PDB file and ignores the rest:

https://github.com/pharmai/plip/blob/c8d4c8dbe9e2f876bfac7acadf424b1f16582aa9/plip/structure/preparation.py#L60

I will consider to implement a command line flag that allows to select the desired model for the next release. For now, could you please use PyMol to isolate your models into separate structures with the `split_states` command (see https://pymolwiki.org/index.php/Split_states)? Then you could analyze all models with a simple bash script or you use a specific one.

**Comment by koyurion** [comment]
Thank you for your help !~
