### ISSUE TITLE
Usermanual

### ISSUE THREAD

**Issue by guiedd** [pharmai/plip#75]
**Is your feature request related to a problem? Please describe.**
It's very hard, at least for me. Processing a lot of molecules using PLIp as part of a python script. I have tried everything for saving png visualization using pymol on various complex but i have got nothing. 

**Describe the solution you'd like**
Add python module manual

**Describe alternatives you've considered**
Add a quick tutorial
**Additional context**

**Comment by fkaiserbio** [comment]
Dear guiedd,

the [README](https://github.com/pharmai/plip#python-module) contains a very detailed section about how to use PLIP in your project.

In a nutshell:

1. download PLIP sources and add the folder to your `PYTHONPATH` environment variable
2. make sure you have installed OpenBabel 3 and its Python bindings correctly, verify with `import pybel`

You may also try via PyPi but this does also **not** install OpenBabel for you. In addition, if you want to create visualizations, please also install PyMOL and its bindings.
