### ISSUE TITLE
Something abnormal while using pdb file prepared by pymol

### ISSUE THREAD

**Issue by zhangshd** [pharmai/plip#79]
**Describe the bug**
Hi, 
I tried to get the interactions using pdb files from PDBbind. For one complex, the raw files from PDBbindwere separated ligand file, pocket file and protein file. I merged the ligand file and the protein file into one [complex pdb file](https://cowtransfer.com/s/fe7a5f8aba4b49) by PyMol. And then extracted interactions by PLIP. But there seems something abnormal in the results as shown in [here](https://projects.biotec.tu-dresden.de/plip-web/plip/result/35d8b102-780b-48db-bace-efef4f6970ea) (R47). ![](https://projects.biotec.tu-dresden.de/plip-web/plip/siteImage/35d8b102-780b-48db-bace-efef4f6970ea?maxWidth=400&maxHeight=400&filename=4GQL_COMPLEX_PROTEIN_R47_R_47.png)
The coordinates of some atoms were in mess. I did the same extraction using [pdb file](https://cowtransfer.com/s/2b5047aea6e545) from RCSB PDB website. And this time the [results](https://projects.biotec.tu-dresden.de/plip-web/plip/result/a8093d8f-27fd-4e4c-bacb-ea84b1c197e2) look normal.
![](https://projects.biotec.tu-dresden.de/plip-web/plip/siteImage/a8093d8f-27fd-4e4c-bacb-ea84b1c197e2?maxWidth=400&maxHeight=400&filename=4GQL_R47_A_306.png)

The extracted interactions were different in two conditions above. Especially the Halogen Bond interaction which I concerned. Indeed, I have not exacted any halogen bond interactions or Metal Complex interactions from any files from PDBbind.
I guess the problem may be in the preparation of input files. It seems that PLIP is more friendly to raw pdb file from RCSB PDB. So why the coordinates of some atoms were in mess after the preparation procedure of PLIP?

**Expected behavior**
Get normal results with pdb file prepared by pymol, just same as the results from using raw pdb file from RCSB PDB.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Environment: 
    - python 3.7.6
    - plip 2.1.4
    - openbabel 3.1.1
   - pymol 2.3.4

Thank you very much.

**Comment by fkaiserbio** [comment]
Dear Shengde,

please be aware that detection of metal complexes relies on `LINK` entry records in PDB files. Could you please check whether they are present in your merged file?

Best
Florian

**Comment by zhangshd** [comment]
> Dear Shengde,
> 
> please be aware that detection of metal complexes relies on `LINK` entry records in PDB files. Could you please check whether they are present in your merged file?
> 
> Best
> Florian

Dear Florian, 

thank you for you support. Indeed, the `LINK` entry records were lost in my merged file. I'll be aware of your suggestion later.


Best,
Shengde
