### ISSUE TITLE
variable hetatoms on the preparation.py file on the master branch is wrong

### ISSUE THREAD

**Issue by chrisxu2016** [pharmai/plip#84]
https://github.com/pharmai/plip/blob/975b7901637055e680f3fa691fd4ccd87fe232c4/plip/structure/preparation.py#L299

I found an error in line 299 of the preparation.py script on the master branch. Here it should be the cur_hetatoms variable, not the hetatoms variable. This problem has been fixed on the develop branch, please update the master branch as soon as possible

**Comment by fkaiserbio** [comment]
This was done with the new release https://github.com/pharmai/plip/releases/tag/v2.1.5
