### ISSUE TITLE
PyPI plip wheel 2.1.7 is broken.

### ISSUE THREAD

**Issue by zacharyrs** [pharmai/plip#94]
Installing `plip` with `pip install plip` works, but `plip` cannot be run via command line - syntax error at [line 18 of `detection.py`](https://github.com/pharmai/plip/blob/2d995f872aed9ee829f3cc4f939a21d69a6634b3/plip/structure/detection.py#L18).

Seems the wheel has removed `config.INTRA`.

Forcibly installing the archive release works (`pip install plip --no-binary :all:`).

**Comment by fkaiserbio** [comment]
This will be fixed in the new release. Thank you for reporting.
