### ISSUE TITLE
Provide an instruction document to use with python

### ISSUE THREAD

**Issue by ankit1-iitbhu** [pharmai/plip#95]
Kindly include a user manual to use plip in python script. The various attributes and classes that can be used.

**Comment by fkaiserbio** [comment]
Dear @ankit1-iitbhu,

please have a look to the test methods, were you find a lot of code how to use the Python back-end. If you are less-experienced with Python, we highly recommend to go with the Docker image:

```bash
$ docker run --rm \
    -v ${PWD}:/results \
    -w /results \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    pharmai/plip:latest -i 1s3v -yv
```

Characterizing a complex is as easy as the following code snippet:
```python
pdb_complex = PDBComplex()
pdb_complex.load_pdb('./pdb/4day.pdb')
for ligand in pdb_complex.ligands:
    pdb_complex.characterize_complex(ligand)
[DO SOMETHING HERE]
```
