### ISSUE TITLE
Would it be possible to include peptide-protein interactions for the python library. Example: PDBComplex().load_pdb("file.pdb",peptide="chain")

### ISSUE THREAD

**Issue by AngelRuizMoreno** [pharmai/plip#97]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fkaiserbio** [comment]
This is possible already, for example:

```python
config.PEPTIDES = ['C']
pdb_complex = PDBComplex()
pdb_complex.load_pdb('./pdb/4day.pdb')
for ligand in pdb_complex.ligands:
    pdb_complex.characterize_complex(ligand)
    structure_report = StructureReport(pdb_complex, outputprefix="test_")
    structure_report.write_xml(as_string=True)
```

This code snippet treats chain C of the protein as peptide ligand, by setting the `config.PEPTIDES` variable before calling the analyze routines.
