### ISSUE TITLE
error with the webserver

### ISSUE THREAD

**Issue by hima111997** [pharmai/plip#98]
**Describe the bug**
I am trying to use the webserver to analyze the interaction in a pdb complex file but it gave me this error:
Sorry, your job has been failed for some reason. Please try again or contact us, if the problem still persists.

I tried to run it locally but gave me this:

2021-02-06 17:02:50,323 [INFO] [plipcmd.py:125] plip.plipcmd: Protein-Ligand Interaction Profiler (PLIP) 2.1.7
2021-02-06 17:02:50,324 [INFO] [plipcmd.py:126] plip.plipcmd: brought to you by: PharmAI GmbH (2020) - www.pharm.ai - hello@pharm.ai
2021-02-06 17:02:50,324 [INFO] [plipcmd.py:127] plip.plipcmd: please cite: https://www.doi.org/10.1093/nar/gkv315
2021-02-06 17:02:50,324 [INFO] [plipcmd.py:50] plip.plipcmd: starting analysis of 22.5_Chitosan.pdb
2021-02-06 17:02:50,348 [ERROR] [supplemental.py:404] plip.basic.supplemental: no valid file format provided

what is the error?

Thanks

**Comment by fkaiserbio** [comment]
Dear hima111997,

thanks for reporting the issue. There is most likely a format issue with your input file. Can you please provide it?

**Comment by hima111997** [comment]
This is one of the files that produced this error

Sent from Yahoo Mail on Android 
 
  On الاثنين, فبراير ٨, ٢٠٢١ at ١٠:٠٢ ص, Florian Kaiser<notifications@github.com> wrote:   


Dear hima111997,

thanks for reporting the issue. There is most likely a format issue with your input file. Can you please provide it?

**Comment by hima111997** [comment]
[22.5_Chitosan.zip](https://github.com/pharmai/plip/files/5967418/22.5_Chitosan.zip)

I am very sorry. I attached the file in yahoo mail but today I discovered that it was not sent.
this is one of the files that produced the error

**Comment by fkaiserbio** [comment]
Hi @hima111997,

the atom names in your PDB file do not follow the standard names for amino acids. I think this is the problem and PLIP cannot know how to detect interactions then.

**Comment by hima111997** [comment]
I changed the atom names and it worked on the server, however, the shape of the ligand got distorted. 
![image](https://user-images.githubusercontent.com/55895327/108053183-bec45100-7055-11eb-9ca8-d72944ad4086.png)

**Comment by hima111997** [comment]
the problem was solved by removing all hydrogen from structure, saving the file using chimera then upload it

**Comment by fkaiserbio** [comment]
Great! Thank you for the feedback. Problems in visualization do not necessarily mean PLIP failed. Usually it point to missing CONECT entries in the PDB file.
